#!/bin/bash
# description: AlmaLinux base Docker image rootfs and Dockerfile generation
#              script.
# license: MIT.

set -euo pipefail
# for type in default minimal base micro init; 
for type in micro minimal base init; 
do
    for arch in amd64 arm64v8 ppc64le;

    do
        march=$arch;
        if [[ $arch == 'arm64v8' ]]; then
            march='aarch64';
        fi    
        if [[ $arch == 'amd64' ]]; then
            march='x86_64';
        fi   
        build_tag='almalinux/'$arch':8-'$type'-20220512';
        docker build --squash --platform=linux/$arch -t $build_tag -f Dockerfile-$march-$type . 
        docker push $build_tag
        #docker push srbala/staging-alma9:$arch-$type-20220512
        #docker pull srbala/staging-alma9:$arch-$type-20220512
        #./gen-rootfs srbala/staging-alma9:$arch-$type-20220512 $arch $type 
    done
done
#        docker build --no-cache --platform=linux/$arch -t srbala/staging-alma9:$arch-$type20220512 -f Dockerfile.$type . 
#        docker push srbala/staging-alma9:$arch-$type-20220512

# for type in micro minimal default base init; 

# do 
#     # docker manifest rm srbala/staging-alma9:$type-20220512; \
#     docker manifest create srbala/staging-alma9:$type-20220512 \
#         almalinux/amd64:9-base-20220512 \
#         almalinux/arm64v8:9-base-20220512 \
#         almalinux/ppc64le:9-base-20220512 \
#         almalinux/s390x:9-base-20220512; \
#     docker manifest push srbala/staging-alma9:$type-20220512
# done
