#!/bin/bash
# description: AlmaLinux base Docker image rootfs and Dockerfile generation
#              script.
# license: MIT.

set -euo pipefail
for type in micro minimal base init; 
do 
    docker manifest rm almalinux/8-$type:8.6
    docker manifest rm almalinux/8-$type:8
    docker manifest rm almalinux/8-$type:latest
    docker manifest rm almalinux/8-$type:8.6-20220512
    for tag in latest 8 8.6 8.6-20220512
    do
        docker manifest create almalinux/8-$type:$tag \
            almalinux/amd64:8-$type-20220512 \
            almalinux/arm64v8:8-$type-20220512 \
            almalinux/ppc64le:8-$type-20220512;
        docker manifest push almalinux/8-$type:$tag
    done
done


    docker manifest rm almalinux/8-$type:8
    docker manifest rm almalinux/8-$type:latest

docker manifest rm quay.io/almalinux/almalinux:8
docker manifest rm quay.io/almalinux/almalinux:latest

docker manifest create quay.io/almalinux/almalinux:8 \
            quay.io/almalinux/amd64:8.6-20220512 \
            quay.io/almalinux/arm64v8:8.6-20220512 \
            quay.io/almalinux/ppc64le:8.6-20220512;
docker manifest push quay.io/almalinux/almalinux:8
docker manifest create quay.io/almalinux/almalinux:latest \
            quay.io/almalinux/amd64:8.6-20220512 \
            quay.io/almalinux/arm64v8:8.6-20220512 \
            quay.io/almalinux/ppc64le:8.6-20220512;
docker manifest push quay.io/almalinux/almalinux:latest
docker manifest create quay.io/almalinux/almalinux:8.6 \
            quay.io/almalinux/amd64:8.6-20220512 \
            quay.io/almalinux/arm64v8:8.6-20220512 \
            quay.io/almalinux/ppc64le:8.6-20220512;
docker manifest push quay.io/almalinux/almalinux:8.6
docker manifest create quay.io/almalinux/almalinux:8.6-20220512 \
            quay.io/almalinux/amd64:8.6-20220512 \
            quay.io/almalinux/arm64v8:8.6-20220512 \
            quay.io/almalinux/ppc64le:8.6-20220512;
docker manifest push quay.io/almalinux/almalinux:8.6-20220512


docker manifest rm quay.io/almalinux/almalinux:8-minimal
docker manifest rm quay.io/almalinux/almalinux:minimal
docker manifest create quay.io/almalinux/almalinux:8-minimal \
            quay.io/almalinux/amd64:8.6-minimal-20220512 \
            quay.io/almalinux/arm64v8:8.6-minimal-20220512 \
            quay.io/almalinux/ppc64le:8.6-minimal-20220512;
docker manifest push quay.io/almalinux/almalinux:8-minimal
docker manifest create quay.io/almalinux/almalinux:minimal \
            quay.io/almalinux/amd64:8.6-minimal-20220512 \
            quay.io/almalinux/arm64v8:8.6-minimal-20220512 \
            quay.io/almalinux/ppc64le:8.6-minimal-20220512;
docker manifest push quay.io/almalinux/almalinux:minimal
docker manifest create quay.io/almalinux/almalinux:8.6-minimal \
            quay.io/almalinux/amd64:8.6-minimal-20220512 \
            quay.io/almalinux/arm64v8:8.6-minimal-20220512 \
            quay.io/almalinux/ppc64le:8.6-minimal-20220512;
docker manifest push quay.io/almalinux/almalinux:8.6-minimal
docker manifest create quay.io/almalinux/almalinux:8.6-minimal-20220512 \
            quay.io/almalinux/amd64:8.6-minimal-20220512 \
            quay.io/almalinux/arm64v8:8.6-minimal-20220512 \
            quay.io/almalinux/ppc64le:8.6-minimal-20220512;
docker manifest push quay.io/almalinux/almalinux:8.6-minimal-20220512

docker manifest rm quay.io/almalinux/8-minimal:latest
docker manifest rm quay.io/almalinux/8-minimal:8
docker manifest create quay.io/almalinux/almalinux:8-minimal \
            quay.io/almalinux/amd64:8.6-minimal-20220512 \
            quay.io/almalinux/arm64v8:8.6-minimal-20220512 \
            quay.io/almalinux/ppc64le:8.6-minimal-20220512;
docker manifest push quay.io/almalinux/almalinux:8-minimal
docker manifest create quay.io/almalinux/almalinux:minimal \
            quay.io/almalinux/amd64:8.6-minimal-20220512 \
            quay.io/almalinux/arm64v8:8.6-minimal-20220512 \
            quay.io/almalinux/ppc64le:8.6-minimal-20220512;
docker manifest push quay.io/almalinux/almalinux:minimal
docker manifest create quay.io/almalinux/almalinux:8.6-minimal \
            quay.io/almalinux/amd64:8.6-minimal-20220512 \
            quay.io/almalinux/arm64v8:8.6-minimal-20220512 \
            quay.io/almalinux/ppc64le:8.6-minimal-20220512;
docker manifest push quay.io/almalinux/almalinux:8.6-minimal
docker manifest create quay.io/almalinux/almalinux:8.6-minimal-20220512 \
            quay.io/almalinux/amd64:8.6-minimal-20220512 \
            quay.io/almalinux/arm64v8:8.6-minimal-20220512 \
            quay.io/almalinux/ppc64le:8.6-minimal-20220512;
docker manifest push quay.io/almalinux/almalinux:8.6-minimal-20220512
